// Code generated by ent, DO NOT EDIT.

package formsubmissiondata

const (
	// Label holds the string label denoting the formsubmissiondata type in the database.
	Label = "form_submission_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubmissionID holds the string denoting the submission_id field in the database.
	FieldSubmissionID = "submission_id"
	// FieldFieldID holds the string denoting the field_id field in the database.
	FieldFieldID = "field_id"
	// FieldFieldValue holds the string denoting the field_value field in the database.
	FieldFieldValue = "field_value"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// Table holds the table name of the formsubmissiondata in the database.
	Table = "form_submission_data"
)

// Columns holds all SQL columns for formsubmissiondata fields.
var Columns = []string{
	FieldID,
	FieldSubmissionID,
	FieldFieldID,
	FieldFieldValue,
	FieldCreateAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
