// Code generated by ent, DO NOT EDIT.

package form

const (
	// Label holds the string label denoting the form type in the database.
	Label = "form"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldIsRelease holds the string denoting the is_release field in the database.
	FieldIsRelease = "is_release"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// Table holds the table name of the form in the database.
	Table = "forms"
)

// Columns holds all SQL columns for form fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldTitle,
	FieldDescription,
	FieldCreateAt,
	FieldUpdateAt,
	FieldIsRelease,
	FieldDisabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsRelease holds the default value on creation for the "is_release" field.
	DefaultIsRelease int
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
