// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"magnum/ent/formfield"
	"magnum/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormFieldQuery is the builder for querying FormField entities.
type FormFieldQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.FormField
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormFieldQuery builder.
func (ffq *FormFieldQuery) Where(ps ...predicate.FormField) *FormFieldQuery {
	ffq.predicates = append(ffq.predicates, ps...)
	return ffq
}

// Limit the number of records to be returned by this query.
func (ffq *FormFieldQuery) Limit(limit int) *FormFieldQuery {
	ffq.ctx.Limit = &limit
	return ffq
}

// Offset to start from.
func (ffq *FormFieldQuery) Offset(offset int) *FormFieldQuery {
	ffq.ctx.Offset = &offset
	return ffq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ffq *FormFieldQuery) Unique(unique bool) *FormFieldQuery {
	ffq.ctx.Unique = &unique
	return ffq
}

// Order specifies how the records should be ordered.
func (ffq *FormFieldQuery) Order(o ...OrderFunc) *FormFieldQuery {
	ffq.order = append(ffq.order, o...)
	return ffq
}

// First returns the first FormField entity from the query.
// Returns a *NotFoundError when no FormField was found.
func (ffq *FormFieldQuery) First(ctx context.Context) (*FormField, error) {
	nodes, err := ffq.Limit(1).All(setContextOp(ctx, ffq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{formfield.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ffq *FormFieldQuery) FirstX(ctx context.Context) *FormField {
	node, err := ffq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FormField ID from the query.
// Returns a *NotFoundError when no FormField ID was found.
func (ffq *FormFieldQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ffq.Limit(1).IDs(setContextOp(ctx, ffq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{formfield.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ffq *FormFieldQuery) FirstIDX(ctx context.Context) string {
	id, err := ffq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FormField entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FormField entity is found.
// Returns a *NotFoundError when no FormField entities are found.
func (ffq *FormFieldQuery) Only(ctx context.Context) (*FormField, error) {
	nodes, err := ffq.Limit(2).All(setContextOp(ctx, ffq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{formfield.Label}
	default:
		return nil, &NotSingularError{formfield.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ffq *FormFieldQuery) OnlyX(ctx context.Context) *FormField {
	node, err := ffq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FormField ID in the query.
// Returns a *NotSingularError when more than one FormField ID is found.
// Returns a *NotFoundError when no entities are found.
func (ffq *FormFieldQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ffq.Limit(2).IDs(setContextOp(ctx, ffq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{formfield.Label}
	default:
		err = &NotSingularError{formfield.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ffq *FormFieldQuery) OnlyIDX(ctx context.Context) string {
	id, err := ffq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FormFields.
func (ffq *FormFieldQuery) All(ctx context.Context) ([]*FormField, error) {
	ctx = setContextOp(ctx, ffq.ctx, "All")
	if err := ffq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FormField, *FormFieldQuery]()
	return withInterceptors[[]*FormField](ctx, ffq, qr, ffq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ffq *FormFieldQuery) AllX(ctx context.Context) []*FormField {
	nodes, err := ffq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FormField IDs.
func (ffq *FormFieldQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ffq.ctx.Unique == nil && ffq.path != nil {
		ffq.Unique(true)
	}
	ctx = setContextOp(ctx, ffq.ctx, "IDs")
	if err = ffq.Select(formfield.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ffq *FormFieldQuery) IDsX(ctx context.Context) []string {
	ids, err := ffq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ffq *FormFieldQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ffq.ctx, "Count")
	if err := ffq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ffq, querierCount[*FormFieldQuery](), ffq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ffq *FormFieldQuery) CountX(ctx context.Context) int {
	count, err := ffq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ffq *FormFieldQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ffq.ctx, "Exist")
	switch _, err := ffq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ffq *FormFieldQuery) ExistX(ctx context.Context) bool {
	exist, err := ffq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormFieldQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ffq *FormFieldQuery) Clone() *FormFieldQuery {
	if ffq == nil {
		return nil
	}
	return &FormFieldQuery{
		config:     ffq.config,
		ctx:        ffq.ctx.Clone(),
		order:      append([]OrderFunc{}, ffq.order...),
		inters:     append([]Interceptor{}, ffq.inters...),
		predicates: append([]predicate.FormField{}, ffq.predicates...),
		// clone intermediate query.
		sql:  ffq.sql.Clone(),
		path: ffq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FormID string `json:"form_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormField.Query().
//		GroupBy(formfield.FieldFormID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ffq *FormFieldQuery) GroupBy(field string, fields ...string) *FormFieldGroupBy {
	ffq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormFieldGroupBy{build: ffq}
	grbuild.flds = &ffq.ctx.Fields
	grbuild.label = formfield.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FormID string `json:"form_id,omitempty"`
//	}
//
//	client.FormField.Query().
//		Select(formfield.FieldFormID).
//		Scan(ctx, &v)
func (ffq *FormFieldQuery) Select(fields ...string) *FormFieldSelect {
	ffq.ctx.Fields = append(ffq.ctx.Fields, fields...)
	sbuild := &FormFieldSelect{FormFieldQuery: ffq}
	sbuild.label = formfield.Label
	sbuild.flds, sbuild.scan = &ffq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormFieldSelect configured with the given aggregations.
func (ffq *FormFieldQuery) Aggregate(fns ...AggregateFunc) *FormFieldSelect {
	return ffq.Select().Aggregate(fns...)
}

func (ffq *FormFieldQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ffq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ffq); err != nil {
				return err
			}
		}
	}
	for _, f := range ffq.ctx.Fields {
		if !formfield.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ffq.path != nil {
		prev, err := ffq.path(ctx)
		if err != nil {
			return err
		}
		ffq.sql = prev
	}
	return nil
}

func (ffq *FormFieldQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FormField, error) {
	var (
		nodes = []*FormField{}
		_spec = ffq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FormField).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FormField{config: ffq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ffq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ffq *FormFieldQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ffq.querySpec()
	_spec.Node.Columns = ffq.ctx.Fields
	if len(ffq.ctx.Fields) > 0 {
		_spec.Unique = ffq.ctx.Unique != nil && *ffq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ffq.driver, _spec)
}

func (ffq *FormFieldQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(formfield.Table, formfield.Columns, sqlgraph.NewFieldSpec(formfield.FieldID, field.TypeString))
	_spec.From = ffq.sql
	if unique := ffq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ffq.path != nil {
		_spec.Unique = true
	}
	if fields := ffq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formfield.FieldID)
		for i := range fields {
			if fields[i] != formfield.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ffq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ffq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ffq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ffq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ffq *FormFieldQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ffq.driver.Dialect())
	t1 := builder.Table(formfield.Table)
	columns := ffq.ctx.Fields
	if len(columns) == 0 {
		columns = formfield.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ffq.sql != nil {
		selector = ffq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ffq.ctx.Unique != nil && *ffq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ffq.predicates {
		p(selector)
	}
	for _, p := range ffq.order {
		p(selector)
	}
	if offset := ffq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ffq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FormFieldGroupBy is the group-by builder for FormField entities.
type FormFieldGroupBy struct {
	selector
	build *FormFieldQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ffgb *FormFieldGroupBy) Aggregate(fns ...AggregateFunc) *FormFieldGroupBy {
	ffgb.fns = append(ffgb.fns, fns...)
	return ffgb
}

// Scan applies the selector query and scans the result into the given value.
func (ffgb *FormFieldGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ffgb.build.ctx, "GroupBy")
	if err := ffgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormFieldQuery, *FormFieldGroupBy](ctx, ffgb.build, ffgb, ffgb.build.inters, v)
}

func (ffgb *FormFieldGroupBy) sqlScan(ctx context.Context, root *FormFieldQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ffgb.fns))
	for _, fn := range ffgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ffgb.flds)+len(ffgb.fns))
		for _, f := range *ffgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ffgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ffgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormFieldSelect is the builder for selecting fields of FormField entities.
type FormFieldSelect struct {
	*FormFieldQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ffs *FormFieldSelect) Aggregate(fns ...AggregateFunc) *FormFieldSelect {
	ffs.fns = append(ffs.fns, fns...)
	return ffs
}

// Scan applies the selector query and scans the result into the given value.
func (ffs *FormFieldSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ffs.ctx, "Select")
	if err := ffs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormFieldQuery, *FormFieldSelect](ctx, ffs.FormFieldQuery, ffs, ffs.inters, v)
}

func (ffs *FormFieldSelect) sqlScan(ctx context.Context, root *FormFieldQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ffs.fns))
	for _, fn := range ffs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ffs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ffs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
