// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"magnum/ent/formfieldconfig"
	"magnum/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormFieldConfigQuery is the builder for querying FormFieldConfig entities.
type FormFieldConfigQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.FormFieldConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormFieldConfigQuery builder.
func (ffcq *FormFieldConfigQuery) Where(ps ...predicate.FormFieldConfig) *FormFieldConfigQuery {
	ffcq.predicates = append(ffcq.predicates, ps...)
	return ffcq
}

// Limit the number of records to be returned by this query.
func (ffcq *FormFieldConfigQuery) Limit(limit int) *FormFieldConfigQuery {
	ffcq.ctx.Limit = &limit
	return ffcq
}

// Offset to start from.
func (ffcq *FormFieldConfigQuery) Offset(offset int) *FormFieldConfigQuery {
	ffcq.ctx.Offset = &offset
	return ffcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ffcq *FormFieldConfigQuery) Unique(unique bool) *FormFieldConfigQuery {
	ffcq.ctx.Unique = &unique
	return ffcq
}

// Order specifies how the records should be ordered.
func (ffcq *FormFieldConfigQuery) Order(o ...OrderFunc) *FormFieldConfigQuery {
	ffcq.order = append(ffcq.order, o...)
	return ffcq
}

// First returns the first FormFieldConfig entity from the query.
// Returns a *NotFoundError when no FormFieldConfig was found.
func (ffcq *FormFieldConfigQuery) First(ctx context.Context) (*FormFieldConfig, error) {
	nodes, err := ffcq.Limit(1).All(setContextOp(ctx, ffcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{formfieldconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) FirstX(ctx context.Context) *FormFieldConfig {
	node, err := ffcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FormFieldConfig ID from the query.
// Returns a *NotFoundError when no FormFieldConfig ID was found.
func (ffcq *FormFieldConfigQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ffcq.Limit(1).IDs(setContextOp(ctx, ffcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{formfieldconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) FirstIDX(ctx context.Context) string {
	id, err := ffcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FormFieldConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FormFieldConfig entity is found.
// Returns a *NotFoundError when no FormFieldConfig entities are found.
func (ffcq *FormFieldConfigQuery) Only(ctx context.Context) (*FormFieldConfig, error) {
	nodes, err := ffcq.Limit(2).All(setContextOp(ctx, ffcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{formfieldconfig.Label}
	default:
		return nil, &NotSingularError{formfieldconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) OnlyX(ctx context.Context) *FormFieldConfig {
	node, err := ffcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FormFieldConfig ID in the query.
// Returns a *NotSingularError when more than one FormFieldConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (ffcq *FormFieldConfigQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ffcq.Limit(2).IDs(setContextOp(ctx, ffcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{formfieldconfig.Label}
	default:
		err = &NotSingularError{formfieldconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) OnlyIDX(ctx context.Context) string {
	id, err := ffcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FormFieldConfigs.
func (ffcq *FormFieldConfigQuery) All(ctx context.Context) ([]*FormFieldConfig, error) {
	ctx = setContextOp(ctx, ffcq.ctx, "All")
	if err := ffcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FormFieldConfig, *FormFieldConfigQuery]()
	return withInterceptors[[]*FormFieldConfig](ctx, ffcq, qr, ffcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) AllX(ctx context.Context) []*FormFieldConfig {
	nodes, err := ffcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FormFieldConfig IDs.
func (ffcq *FormFieldConfigQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ffcq.ctx.Unique == nil && ffcq.path != nil {
		ffcq.Unique(true)
	}
	ctx = setContextOp(ctx, ffcq.ctx, "IDs")
	if err = ffcq.Select(formfieldconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) IDsX(ctx context.Context) []string {
	ids, err := ffcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ffcq *FormFieldConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ffcq.ctx, "Count")
	if err := ffcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ffcq, querierCount[*FormFieldConfigQuery](), ffcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) CountX(ctx context.Context) int {
	count, err := ffcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ffcq *FormFieldConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ffcq.ctx, "Exist")
	switch _, err := ffcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ffcq *FormFieldConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := ffcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormFieldConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ffcq *FormFieldConfigQuery) Clone() *FormFieldConfigQuery {
	if ffcq == nil {
		return nil
	}
	return &FormFieldConfigQuery{
		config:     ffcq.config,
		ctx:        ffcq.ctx.Clone(),
		order:      append([]OrderFunc{}, ffcq.order...),
		inters:     append([]Interceptor{}, ffcq.inters...),
		predicates: append([]predicate.FormFieldConfig{}, ffcq.predicates...),
		// clone intermediate query.
		sql:  ffcq.sql.Clone(),
		path: ffcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FieldID string `json:"field_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormFieldConfig.Query().
//		GroupBy(formfieldconfig.FieldFieldID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ffcq *FormFieldConfigQuery) GroupBy(field string, fields ...string) *FormFieldConfigGroupBy {
	ffcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormFieldConfigGroupBy{build: ffcq}
	grbuild.flds = &ffcq.ctx.Fields
	grbuild.label = formfieldconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FieldID string `json:"field_id,omitempty"`
//	}
//
//	client.FormFieldConfig.Query().
//		Select(formfieldconfig.FieldFieldID).
//		Scan(ctx, &v)
func (ffcq *FormFieldConfigQuery) Select(fields ...string) *FormFieldConfigSelect {
	ffcq.ctx.Fields = append(ffcq.ctx.Fields, fields...)
	sbuild := &FormFieldConfigSelect{FormFieldConfigQuery: ffcq}
	sbuild.label = formfieldconfig.Label
	sbuild.flds, sbuild.scan = &ffcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormFieldConfigSelect configured with the given aggregations.
func (ffcq *FormFieldConfigQuery) Aggregate(fns ...AggregateFunc) *FormFieldConfigSelect {
	return ffcq.Select().Aggregate(fns...)
}

func (ffcq *FormFieldConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ffcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ffcq); err != nil {
				return err
			}
		}
	}
	for _, f := range ffcq.ctx.Fields {
		if !formfieldconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ffcq.path != nil {
		prev, err := ffcq.path(ctx)
		if err != nil {
			return err
		}
		ffcq.sql = prev
	}
	return nil
}

func (ffcq *FormFieldConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FormFieldConfig, error) {
	var (
		nodes = []*FormFieldConfig{}
		_spec = ffcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FormFieldConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FormFieldConfig{config: ffcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ffcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ffcq *FormFieldConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ffcq.querySpec()
	_spec.Node.Columns = ffcq.ctx.Fields
	if len(ffcq.ctx.Fields) > 0 {
		_spec.Unique = ffcq.ctx.Unique != nil && *ffcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ffcq.driver, _spec)
}

func (ffcq *FormFieldConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(formfieldconfig.Table, formfieldconfig.Columns, sqlgraph.NewFieldSpec(formfieldconfig.FieldID, field.TypeString))
	_spec.From = ffcq.sql
	if unique := ffcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ffcq.path != nil {
		_spec.Unique = true
	}
	if fields := ffcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formfieldconfig.FieldID)
		for i := range fields {
			if fields[i] != formfieldconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ffcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ffcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ffcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ffcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ffcq *FormFieldConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ffcq.driver.Dialect())
	t1 := builder.Table(formfieldconfig.Table)
	columns := ffcq.ctx.Fields
	if len(columns) == 0 {
		columns = formfieldconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ffcq.sql != nil {
		selector = ffcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ffcq.ctx.Unique != nil && *ffcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ffcq.predicates {
		p(selector)
	}
	for _, p := range ffcq.order {
		p(selector)
	}
	if offset := ffcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ffcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FormFieldConfigGroupBy is the group-by builder for FormFieldConfig entities.
type FormFieldConfigGroupBy struct {
	selector
	build *FormFieldConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ffcgb *FormFieldConfigGroupBy) Aggregate(fns ...AggregateFunc) *FormFieldConfigGroupBy {
	ffcgb.fns = append(ffcgb.fns, fns...)
	return ffcgb
}

// Scan applies the selector query and scans the result into the given value.
func (ffcgb *FormFieldConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ffcgb.build.ctx, "GroupBy")
	if err := ffcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormFieldConfigQuery, *FormFieldConfigGroupBy](ctx, ffcgb.build, ffcgb, ffcgb.build.inters, v)
}

func (ffcgb *FormFieldConfigGroupBy) sqlScan(ctx context.Context, root *FormFieldConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ffcgb.fns))
	for _, fn := range ffcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ffcgb.flds)+len(ffcgb.fns))
		for _, f := range *ffcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ffcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ffcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormFieldConfigSelect is the builder for selecting fields of FormFieldConfig entities.
type FormFieldConfigSelect struct {
	*FormFieldConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ffcs *FormFieldConfigSelect) Aggregate(fns ...AggregateFunc) *FormFieldConfigSelect {
	ffcs.fns = append(ffcs.fns, fns...)
	return ffcs
}

// Scan applies the selector query and scans the result into the given value.
func (ffcs *FormFieldConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ffcs.ctx, "Select")
	if err := ffcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormFieldConfigQuery, *FormFieldConfigSelect](ctx, ffcs.FormFieldConfigQuery, ffcs, ffcs.inters, v)
}

func (ffcs *FormFieldConfigSelect) sqlScan(ctx context.Context, root *FormFieldConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ffcs.fns))
	for _, fn := range ffcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ffcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ffcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
