// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"magnum/ent/form"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormCreate is the builder for creating a Form entity.
type FormCreate struct {
	config
	mutation *FormMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (fc *FormCreate) SetUserID(s string) *FormCreate {
	fc.mutation.SetUserID(s)
	return fc
}

// SetTitle sets the "title" field.
func (fc *FormCreate) SetTitle(s string) *FormCreate {
	fc.mutation.SetTitle(s)
	return fc
}

// SetDescription sets the "description" field.
func (fc *FormCreate) SetDescription(s string) *FormCreate {
	fc.mutation.SetDescription(s)
	return fc
}

// SetCreateAt sets the "create_at" field.
func (fc *FormCreate) SetCreateAt(t time.Time) *FormCreate {
	fc.mutation.SetCreateAt(t)
	return fc
}

// SetUpdateAt sets the "update_at" field.
func (fc *FormCreate) SetUpdateAt(t time.Time) *FormCreate {
	fc.mutation.SetUpdateAt(t)
	return fc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (fc *FormCreate) SetNillableUpdateAt(t *time.Time) *FormCreate {
	if t != nil {
		fc.SetUpdateAt(*t)
	}
	return fc
}

// SetID sets the "id" field.
func (fc *FormCreate) SetID(s string) *FormCreate {
	fc.mutation.SetID(s)
	return fc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fc *FormCreate) SetNillableID(s *string) *FormCreate {
	if s != nil {
		fc.SetID(*s)
	}
	return fc
}

// Mutation returns the FormMutation object of the builder.
func (fc *FormCreate) Mutation() *FormMutation {
	return fc.mutation
}

// Save creates the Form in the database.
func (fc *FormCreate) Save(ctx context.Context) (*Form, error) {
	fc.defaults()
	return withHooks[*Form, FormMutation](ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FormCreate) SaveX(ctx context.Context) *Form {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FormCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FormCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FormCreate) defaults() {
	if _, ok := fc.mutation.ID(); !ok {
		v := form.DefaultID()
		fc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FormCreate) check() error {
	if _, ok := fc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Form.user_id"`)}
	}
	if _, ok := fc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Form.title"`)}
	}
	if _, ok := fc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Form.description"`)}
	}
	if _, ok := fc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "Form.create_at"`)}
	}
	return nil
}

func (fc *FormCreate) sqlSave(ctx context.Context) (*Form, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Form.ID type: %T", _spec.ID.Value)
		}
	}
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FormCreate) createSpec() (*Form, *sqlgraph.CreateSpec) {
	var (
		_node = &Form{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(form.Table, sqlgraph.NewFieldSpec(form.FieldID, field.TypeString))
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := fc.mutation.UserID(); ok {
		_spec.SetField(form.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := fc.mutation.Title(); ok {
		_spec.SetField(form.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := fc.mutation.Description(); ok {
		_spec.SetField(form.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := fc.mutation.CreateAt(); ok {
		_spec.SetField(form.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := fc.mutation.UpdateAt(); ok {
		_spec.SetField(form.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// FormCreateBulk is the builder for creating many Form entities in bulk.
type FormCreateBulk struct {
	config
	builders []*FormCreate
}

// Save creates the Form entities in the database.
func (fcb *FormCreateBulk) Save(ctx context.Context) ([]*Form, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Form, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FormMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FormCreateBulk) SaveX(ctx context.Context) []*Form {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FormCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FormCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
