// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"magnum/ent/formsubmission"
	"magnum/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormSubmissionQuery is the builder for querying FormSubmission entities.
type FormSubmissionQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.FormSubmission
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormSubmissionQuery builder.
func (fsq *FormSubmissionQuery) Where(ps ...predicate.FormSubmission) *FormSubmissionQuery {
	fsq.predicates = append(fsq.predicates, ps...)
	return fsq
}

// Limit the number of records to be returned by this query.
func (fsq *FormSubmissionQuery) Limit(limit int) *FormSubmissionQuery {
	fsq.ctx.Limit = &limit
	return fsq
}

// Offset to start from.
func (fsq *FormSubmissionQuery) Offset(offset int) *FormSubmissionQuery {
	fsq.ctx.Offset = &offset
	return fsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsq *FormSubmissionQuery) Unique(unique bool) *FormSubmissionQuery {
	fsq.ctx.Unique = &unique
	return fsq
}

// Order specifies how the records should be ordered.
func (fsq *FormSubmissionQuery) Order(o ...OrderFunc) *FormSubmissionQuery {
	fsq.order = append(fsq.order, o...)
	return fsq
}

// First returns the first FormSubmission entity from the query.
// Returns a *NotFoundError when no FormSubmission was found.
func (fsq *FormSubmissionQuery) First(ctx context.Context) (*FormSubmission, error) {
	nodes, err := fsq.Limit(1).All(setContextOp(ctx, fsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{formsubmission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsq *FormSubmissionQuery) FirstX(ctx context.Context) *FormSubmission {
	node, err := fsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FormSubmission ID from the query.
// Returns a *NotFoundError when no FormSubmission ID was found.
func (fsq *FormSubmissionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = fsq.Limit(1).IDs(setContextOp(ctx, fsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{formsubmission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsq *FormSubmissionQuery) FirstIDX(ctx context.Context) string {
	id, err := fsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FormSubmission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FormSubmission entity is found.
// Returns a *NotFoundError when no FormSubmission entities are found.
func (fsq *FormSubmissionQuery) Only(ctx context.Context) (*FormSubmission, error) {
	nodes, err := fsq.Limit(2).All(setContextOp(ctx, fsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{formsubmission.Label}
	default:
		return nil, &NotSingularError{formsubmission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsq *FormSubmissionQuery) OnlyX(ctx context.Context) *FormSubmission {
	node, err := fsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FormSubmission ID in the query.
// Returns a *NotSingularError when more than one FormSubmission ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsq *FormSubmissionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = fsq.Limit(2).IDs(setContextOp(ctx, fsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{formsubmission.Label}
	default:
		err = &NotSingularError{formsubmission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsq *FormSubmissionQuery) OnlyIDX(ctx context.Context) string {
	id, err := fsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FormSubmissions.
func (fsq *FormSubmissionQuery) All(ctx context.Context) ([]*FormSubmission, error) {
	ctx = setContextOp(ctx, fsq.ctx, "All")
	if err := fsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FormSubmission, *FormSubmissionQuery]()
	return withInterceptors[[]*FormSubmission](ctx, fsq, qr, fsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fsq *FormSubmissionQuery) AllX(ctx context.Context) []*FormSubmission {
	nodes, err := fsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FormSubmission IDs.
func (fsq *FormSubmissionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if fsq.ctx.Unique == nil && fsq.path != nil {
		fsq.Unique(true)
	}
	ctx = setContextOp(ctx, fsq.ctx, "IDs")
	if err = fsq.Select(formsubmission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsq *FormSubmissionQuery) IDsX(ctx context.Context) []string {
	ids, err := fsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsq *FormSubmissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Count")
	if err := fsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fsq, querierCount[*FormSubmissionQuery](), fsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fsq *FormSubmissionQuery) CountX(ctx context.Context) int {
	count, err := fsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsq *FormSubmissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Exist")
	switch _, err := fsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fsq *FormSubmissionQuery) ExistX(ctx context.Context) bool {
	exist, err := fsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormSubmissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsq *FormSubmissionQuery) Clone() *FormSubmissionQuery {
	if fsq == nil {
		return nil
	}
	return &FormSubmissionQuery{
		config:     fsq.config,
		ctx:        fsq.ctx.Clone(),
		order:      append([]OrderFunc{}, fsq.order...),
		inters:     append([]Interceptor{}, fsq.inters...),
		predicates: append([]predicate.FormSubmission{}, fsq.predicates...),
		// clone intermediate query.
		sql:  fsq.sql.Clone(),
		path: fsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FormID string `json:"form_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormSubmission.Query().
//		GroupBy(formsubmission.FieldFormID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fsq *FormSubmissionQuery) GroupBy(field string, fields ...string) *FormSubmissionGroupBy {
	fsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormSubmissionGroupBy{build: fsq}
	grbuild.flds = &fsq.ctx.Fields
	grbuild.label = formsubmission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FormID string `json:"form_id,omitempty"`
//	}
//
//	client.FormSubmission.Query().
//		Select(formsubmission.FieldFormID).
//		Scan(ctx, &v)
func (fsq *FormSubmissionQuery) Select(fields ...string) *FormSubmissionSelect {
	fsq.ctx.Fields = append(fsq.ctx.Fields, fields...)
	sbuild := &FormSubmissionSelect{FormSubmissionQuery: fsq}
	sbuild.label = formsubmission.Label
	sbuild.flds, sbuild.scan = &fsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormSubmissionSelect configured with the given aggregations.
func (fsq *FormSubmissionQuery) Aggregate(fns ...AggregateFunc) *FormSubmissionSelect {
	return fsq.Select().Aggregate(fns...)
}

func (fsq *FormSubmissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fsq); err != nil {
				return err
			}
		}
	}
	for _, f := range fsq.ctx.Fields {
		if !formsubmission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsq.path != nil {
		prev, err := fsq.path(ctx)
		if err != nil {
			return err
		}
		fsq.sql = prev
	}
	return nil
}

func (fsq *FormSubmissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FormSubmission, error) {
	var (
		nodes = []*FormSubmission{}
		_spec = fsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FormSubmission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FormSubmission{config: fsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fsq *FormSubmissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fsq.querySpec()
	_spec.Node.Columns = fsq.ctx.Fields
	if len(fsq.ctx.Fields) > 0 {
		_spec.Unique = fsq.ctx.Unique != nil && *fsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fsq.driver, _spec)
}

func (fsq *FormSubmissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(formsubmission.Table, formsubmission.Columns, sqlgraph.NewFieldSpec(formsubmission.FieldID, field.TypeString))
	_spec.From = fsq.sql
	if unique := fsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fsq.path != nil {
		_spec.Unique = true
	}
	if fields := fsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formsubmission.FieldID)
		for i := range fields {
			if fields[i] != formsubmission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsq *FormSubmissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsq.driver.Dialect())
	t1 := builder.Table(formsubmission.Table)
	columns := fsq.ctx.Fields
	if len(columns) == 0 {
		columns = formsubmission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsq.sql != nil {
		selector = fsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsq.ctx.Unique != nil && *fsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fsq.predicates {
		p(selector)
	}
	for _, p := range fsq.order {
		p(selector)
	}
	if offset := fsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FormSubmissionGroupBy is the group-by builder for FormSubmission entities.
type FormSubmissionGroupBy struct {
	selector
	build *FormSubmissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fsgb *FormSubmissionGroupBy) Aggregate(fns ...AggregateFunc) *FormSubmissionGroupBy {
	fsgb.fns = append(fsgb.fns, fns...)
	return fsgb
}

// Scan applies the selector query and scans the result into the given value.
func (fsgb *FormSubmissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fsgb.build.ctx, "GroupBy")
	if err := fsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormSubmissionQuery, *FormSubmissionGroupBy](ctx, fsgb.build, fsgb, fsgb.build.inters, v)
}

func (fsgb *FormSubmissionGroupBy) sqlScan(ctx context.Context, root *FormSubmissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fsgb.fns))
	for _, fn := range fsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fsgb.flds)+len(fsgb.fns))
		for _, f := range *fsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormSubmissionSelect is the builder for selecting fields of FormSubmission entities.
type FormSubmissionSelect struct {
	*FormSubmissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fss *FormSubmissionSelect) Aggregate(fns ...AggregateFunc) *FormSubmissionSelect {
	fss.fns = append(fss.fns, fns...)
	return fss
}

// Scan applies the selector query and scans the result into the given value.
func (fss *FormSubmissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fss.ctx, "Select")
	if err := fss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormSubmissionQuery, *FormSubmissionSelect](ctx, fss.FormSubmissionQuery, fss, fss.inters, v)
}

func (fss *FormSubmissionSelect) sqlScan(ctx context.Context, root *FormSubmissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fss.fns))
	for _, fn := range fss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
