// Code generated by ent, DO NOT EDIT.

package ent

import (
	"magnum/ent/form"
	"magnum/ent/formfield"
	"magnum/ent/formsubmission"
	"magnum/ent/formsubmissiondata"
	"magnum/ent/schema"
	"magnum/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	formFields := schema.Form{}.Fields()
	_ = formFields
	// formDescID is the schema descriptor for id field.
	formDescID := formFields[0].Descriptor()
	// form.DefaultID holds the default value on creation for the id field.
	form.DefaultID = formDescID.Default.(func() string)
	formfieldFields := schema.FormField{}.Fields()
	_ = formfieldFields
	// formfieldDescIsRequired is the schema descriptor for is_required field.
	formfieldDescIsRequired := formfieldFields[5].Descriptor()
	// formfield.DefaultIsRequired holds the default value on creation for the is_required field.
	formfield.DefaultIsRequired = formfieldDescIsRequired.Default.(int)
	// formfieldDescID is the schema descriptor for id field.
	formfieldDescID := formfieldFields[0].Descriptor()
	// formfield.DefaultID holds the default value on creation for the id field.
	formfield.DefaultID = formfieldDescID.Default.(func() string)
	formsubmissionFields := schema.FormSubmission{}.Fields()
	_ = formsubmissionFields
	// formsubmissionDescID is the schema descriptor for id field.
	formsubmissionDescID := formsubmissionFields[0].Descriptor()
	// formsubmission.DefaultID holds the default value on creation for the id field.
	formsubmission.DefaultID = formsubmissionDescID.Default.(func() string)
	formsubmissiondataFields := schema.FormSubmissionData{}.Fields()
	_ = formsubmissiondataFields
	// formsubmissiondataDescID is the schema descriptor for id field.
	formsubmissiondataDescID := formsubmissiondataFields[0].Descriptor()
	// formsubmissiondata.DefaultID holds the default value on creation for the id field.
	formsubmissiondata.DefaultID = formsubmissiondataDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
