// Code generated by ent, DO NOT EDIT.

package formfield

const (
	// Label holds the string label denoting the formfield type in the database.
	Label = "form_field"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFormID holds the string denoting the form_id field in the database.
	FieldFormID = "form_id"
	// FieldFieldType holds the string denoting the field_type field in the database.
	FieldFieldType = "field_type"
	// FieldFieldLabel holds the string denoting the field_label field in the database.
	FieldFieldLabel = "field_label"
	// FieldFiledName holds the string denoting the filed_name field in the database.
	FieldFiledName = "filed_name"
	// FieldIsRequired holds the string denoting the is_required field in the database.
	FieldIsRequired = "is_required"
	// FieldOrderIndex holds the string denoting the order_index field in the database.
	FieldOrderIndex = "order_index"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldOptions holds the string denoting the options field in the database.
	FieldOptions = "options"
	// FieldPlaceholder holds the string denoting the placeholder field in the database.
	FieldPlaceholder = "placeholder"
	// Table holds the table name of the formfield in the database.
	Table = "form_fields"
)

// Columns holds all SQL columns for formfield fields.
var Columns = []string{
	FieldID,
	FieldFormID,
	FieldFieldType,
	FieldFieldLabel,
	FieldFiledName,
	FieldIsRequired,
	FieldOrderIndex,
	FieldCreateAt,
	FieldUpdateAt,
	FieldOptions,
	FieldPlaceholder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsRequired holds the default value on creation for the "is_required" field.
	DefaultIsRequired int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
