// Code generated by ent, DO NOT EDIT.

package formsubmission

const (
	// Label holds the string label denoting the formsubmission type in the database.
	Label = "form_submission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFormID holds the string denoting the form_id field in the database.
	FieldFormID = "form_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// Table holds the table name of the formsubmission in the database.
	Table = "form_submissions"
)

// Columns holds all SQL columns for formsubmission fields.
var Columns = []string{
	FieldID,
	FieldFormID,
	FieldUserID,
	FieldCreateAt,
	FieldIsDeleted,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
