// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Form is the predicate function for form builders.
type Form func(*sql.Selector)

// FormField is the predicate function for formfield builders.
type FormField func(*sql.Selector)

// FormSubmission is the predicate function for formsubmission builders.
type FormSubmission func(*sql.Selector)

// FormSubmissionData is the predicate function for formsubmissiondata builders.
type FormSubmissionData func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
